#!/bin/sh -e
commit=$(git hash-object -t commit -w --stdin <<END
tree $(git hash-object -t tree -- /dev/null)
author nobody <nobody@localhost> 0 +0000
committer nobody <nobody@localhost> 0 +0000

END
)
git update-ref --no-deref refs/tags/0 "$(git hash-object -t tag -w --stdin <<END
object $commit
type commit
tag 0
tagger nobody <nobody@localhost> 0 +0000

END
)"
git rev-parse HEAD^{object} >/dev/null 2>&1 || git reset "$commit"
git log -1 "$commit"
